### ISSUE TITLE
To do for Milestone 4

### ISSUE THREAD

**Issue by EvanYathon** [UBC-MDS/worldly-wines#21]
- [x] Add a usage/introduction tab

- [x]  Change the `price` density estimate figure to a frequency polygon

- [x] Change order of distribution plots to being stacked vertically

- [x] Improve aesthetics on plots

- [x] Milestone 4 Writeup

- [x] Update `README.md` with new file locations from file structure change 

- [x] Reupload to shinyapps.io
