### ISSUE TITLE
Milestone 2 To Do

### ISSUE THREAD

**Issue by EvanYathon** [UBC-MDS/worldly-wines#6]
- [x] Code of Conduct (Bonnie)

- [x]  Write data cleaning script (Bonnie)

- [x] Create first draft of shiny app (Bonnie and Evan)

- [x] Include screenshots of app and document functionality in MD file in repo (Bonnie)

- [x] Deploy on shinyapps.io (Evan)

- [x] Tag a release v1.0 (Evan)

- [x] Writeup (Evan)

**Comment by EvanYathon** [comment]
Bonnie: screenshots, code of conduct, data cleaning script
Evan: writeup, release, deployment
Bonnie and Evan: first draft of shiny app
